- name: Include group vaulted files
  include_vars:
    dir: "{{playbook_dir}}/vault"
    extensions: ['']
    files_matching: "{{item}}"
  with_items: "{{group_names}}"
  when: " (playbook_dir + '/vault') | dir_exists"
  delegate_to: localhost
  tags:
    - always

- name: Create directories
  file:
    state: directory
    path: "{{item.key | dirname}}"
  with_dict: "{{files}}"

- name: Copy vaulted files
  copy:
    dest: "{{item.key}}"
    src: "{{item.value}}"
  with_dict: "{{files | default({})}}"

- name: Create template directories
  file:
    state: directory
    path: "{{item.key | dirname}}"
  with_dict: "{{templates}}"

- name: Copy templated files
  template:
    dest: "{{item.key}}"
    src: "{{item.value}}"
  with_dict: "{{templates }}"

- name: Create mount points
  file:
      state: directory
      path: "{{item.key}}"
  with_dict: "{{mounts}}"

- name: Sysctls
  sysctl:
    name: "{{item.key}}"
    value: "{{item.value}}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: "{{sysctls}}"

- name: Mount mounts
  mount:
    path: "{{item.key}}"
    src: "{{item.value}}"
    fstype: nfs
    state: mounted
  with_dict: "{{mounts}}"

- name: Save environment variables
  include: environment.yml
  with_dict: "{{env_vars}}"

- name: Execute commands
  shell: "{{item}}"
  with_items: "{{commands}}"
  when: commands is defined

- name: Installing systemd based docker services
  include_tasks: docker_service.yml
  with_items: "{{containers}}"
  loop_control:
    loop_var: container
