
  - file: path="{{inventory_dir}}/build/" state=directory
  - name: rendering user-data for {{inventory_hostname}}
    local_action: template src="cloudinit.tpl" dest="{{inventory_dir}}/build/{{inventory_hostname}}.txt"
    register: temp

  - debug: var=temp
